### ISSUE TITLE
Invalid HTTP request received

### ISSUE THREAD

**Issue by Maclean-D** [justinsunyt/MultiAgent#2]
Trying to open a new chat gives the error "Invalid HTTP request received in multionchat-platform terminal and "TypeError: Failed to Fetch" on the website.
![image](https://github.com/justinsunyt/multionchat-platform/assets/65423362/e8879a01-b6b9-490a-8bfd-03259fa642d2)

**Comment by justinsunyt** [comment]
Hey, I just updated the setup instructions on the readme. Check to see if your Supabase is setup accordingly, the issue is most likely caused by querying a nonexistent table lol.

**Comment by justinsunyt** [comment]
Nevermind, I found the bug: the fetch and post URLs in the frontend is https, but if developing locally it should use http. I will push a fix ASAP.

**Comment by justinsunyt** [comment]
@Maclean-D Please try the latest commit!

**Comment by Maclean-D** [comment]
Completely reinstalled it and still get `TypeError: Failed to Fetch` on the website and this is what the backend spits out:
```
mac@macroom:~/MultiAgent/backend$ pipenv shell
Loading .env environment variables...
Loading .env environment variables...
Launching subshell in virtual environment...
 . /home/mac/.local/share/virtualenvs/backend-YiaDXPIV/bin/activate
mac@macroom:~/MultiAgent/backend$  . /home/mac/.local/share/virtualenvs/backend-YiaDXPIV/bin/activate
(backend) mac@macroom:~/MultiAgent/backend$ pipenv install
Loading .env environment variables...
Installing dependencies from Pipfile.lock (4ca78a)...
(backend) mac@macroom:~/MultiAgent/backend$ uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['/home/mac/MultiAgent/backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [74298] using WatchFiles
INFO:     Started server process [74300]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:43244 - "GET /chat/get_by_model/llava-13b HTTP/1.1" 200 OK
INFO:     127.0.0.1:43250 - "GET /chat/get_by_model/llava-v1.6-34b HTTP/1.1" 200 OK
INFO:     127.0.0.1:43254 - "GET /chat/get_by_model/qwen-vl-chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:46712 - "OPTIONS /chat/get_by_model/llava-13b HTTP/1.1" 200 OK
INFO:     127.0.0.1:46720 - "OPTIONS /chat/get_by_model/llava-v1.6-34b HTTP/1.1" 200 OK
INFO:     127.0.0.1:46712 - "GET /chat/get_by_model/llava-13b HTTP/1.1" 200 OK
INFO:     127.0.0.1:46720 - "GET /chat/get_by_model/llava-v1.6-34b HTTP/1.1" 200 OK
INFO:     127.0.0.1:46734 - "OPTIONS /chat/get_by_model/qwen-vl-chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:46734 - "GET /chat/get_by_model/qwen-vl-chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:52458 - "OPTIONS /chat/create/llava-13b HTTP/1.1" 200 OK
INFO:     127.0.0.1:52458 - "POST /chat/create/llava-13b HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/MultiAgent/backend/routes/chat_router.py", line 68, in create_chat_handler
    response = create_chat(request.app.supabase, model, uid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/MultiAgent/backend/models/chat.py", line 379, in create_chat
    .execute()
     ^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '23502', 'details': None, 'hint': None, 'message': 'null value in column "created_at" of relation "chats" violates not-null constraint'}
INFO:     127.0.0.1:34776 - "GET /chat/get_by_model/llava-13b HTTP/1.1" 200 OK
INFO:     127.0.0.1:34792 - "GET /chat/get_by_model/llava-v1.6-34b HTTP/1.1" 200 OK
INFO:     127.0.0.1:34796 - "GET /chat/get_by_model/qwen-vl-chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:52474 - "OPTIONS /chat/create/qwen-vl-chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:52474 - "POST /chat/create/qwen-vl-chat HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/MultiAgent/backend/routes/chat_router.py", line 68, in create_chat_handler
    response = create_chat(request.app.supabase, model, uid)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/MultiAgent/backend/models/chat.py", line 379, in create_chat
    .execute()
     ^^^^^^^^^
  File "/home/mac/.local/share/virtualenvs/backend-YiaDXPIV/lib/python3.11/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '23502', 'details': None, 'hint': None, 'message': 'null value in column "created_at" of relation "chats" violates not-null constraint'}
```


This is how my supabase is configured:
![image](https://github.com/justinsunyt/MultiAgent/assets/65423362/7192ff12-da30-4c94-b427-7ff1e090782c)

**Comment by Maclean-D** [comment]
nevermind misconfig with Supabase
